#!/usr/bin/env bash

set -E
set -e
set -u
set -o monitor

olad &
/wait-for-it localhost:9010

function ola_enable {
    local plugin_id=$1
    # Enable the plugin.
    ola_plugin_state -p $plugin_id -s enable
    # Assert the plugin is enabled. We cannot rely on ola_plugin_state's exit code, so parse the status output instead.
    ola_plugin_state -p $plugin_id | grep 'Enabled: True'
}

PLUGINS="1:DUMMY
2:ARTNET
3:SHOWNET
4:ESPNET
5:USBSERIAL
6:OPENDMX
7:SANDNET
8:STAGEPROFI
9:PARTHPORT
11:E131
13:FTDIDMX
14:OSC
15:SPI
16:KINET
17:KARATE
18:MILINST
19:RENARD
20:UARTDMX
21:OPENPIXELCONTROL
22:GPIO"
for plugin in $PLUGINS; do
    plugin_parts=(${plugin//\:/ })
    plugin_id=${plugin_parts[0]}
    plugin_name=${plugin_parts[1]}
    env_name=OLA_PLUGIN_$plugin_name
    if [ ! -z "${!env_name}" ]; then
        echo "Enabling OLA plugin $plugin_name ($plugin_id)..."
        ola_enable $plugin_id
    fi
done

fg
