#!/usr/bin/env bash
# Test using a custom entrypoint.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./src/bash/docker

docker run -d --name "$CONTAINER_NAME" --entrypoint olad bartfeenstra/ola:test --http-port 9091
./vendor/bin/wait-for-it "$(container_ip):9091"
