#!/usr/bin/env bash
# Test using a custom entrypoint.

set -e

cd `dirname "$0"`/..

. ./src/bash/docker

docker run -d --name $CONTAINER_NAME --entrypoint olad bartfeenstra/ola:test --http-port 9091
docker logs $CONTAINER_NAME
./bin/wait-for-it `container_ip`:9091
