#!/usr/bin/env bash
# Connect to the web UI.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./src/bash/docker

docker run -d --name "$CONTAINER_NAME" bartfeenstra/ola:test
./vendor/bin/wait-for-it "$(container_ip):9090"
curl --verbose -f "http://$(container_ip):9090" > /dev/null
